FROM golang:1.19.2-bullseye

WORKDIR /app-server

COPY go.mod ./
COPY go.sum ./
COPY proto ./proto

RUN go mod download

COPY server/server.go ./

RUN go build -o /server-bin

EXPOSE 50051

CMD [ "/server-bin" ]