// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateClient interface {
	// send message
	SendChatMessage(ctx context.Context, opts ...grpc.CallOption) (Template_SendChatMessageClient, error)
}

type templateClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateClient(cc grpc.ClientConnInterface) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) SendChatMessage(ctx context.Context, opts ...grpc.CallOption) (Template_SendChatMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Template_ServiceDesc.Streams[0], "/proto.Template/SendChatMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &templateSendChatMessageClient{stream}
	return x, nil
}

type Template_SendChatMessageClient interface {
	Send(*OutgoingMessage) error
	Recv() (*IncomingMessage, error)
	grpc.ClientStream
}

type templateSendChatMessageClient struct {
	grpc.ClientStream
}

func (x *templateSendChatMessageClient) Send(m *OutgoingMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *templateSendChatMessageClient) Recv() (*IncomingMessage, error) {
	m := new(IncomingMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TemplateServer is the server API for Template service.
// All implementations must embed UnimplementedTemplateServer
// for forward compatibility
type TemplateServer interface {
	// send message
	SendChatMessage(Template_SendChatMessageServer) error
	mustEmbedUnimplementedTemplateServer()
}

// UnimplementedTemplateServer must be embedded to have forward compatible implementations.
type UnimplementedTemplateServer struct {
}

func (UnimplementedTemplateServer) SendChatMessage(Template_SendChatMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendChatMessage not implemented")
}
func (UnimplementedTemplateServer) mustEmbedUnimplementedTemplateServer() {}

// UnsafeTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServer will
// result in compilation errors.
type UnsafeTemplateServer interface {
	mustEmbedUnimplementedTemplateServer()
}

func RegisterTemplateServer(s grpc.ServiceRegistrar, srv TemplateServer) {
	s.RegisterService(&Template_ServiceDesc, srv)
}

func _Template_SendChatMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemplateServer).SendChatMessage(&templateSendChatMessageServer{stream})
}

type Template_SendChatMessageServer interface {
	Send(*IncomingMessage) error
	Recv() (*OutgoingMessage, error)
	grpc.ServerStream
}

type templateSendChatMessageServer struct {
	grpc.ServerStream
}

func (x *templateSendChatMessageServer) Send(m *IncomingMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *templateSendChatMessageServer) Recv() (*OutgoingMessage, error) {
	m := new(OutgoingMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Template_ServiceDesc is the grpc.ServiceDesc for Template service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Template_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendChatMessage",
			Handler:       _Template_SendChatMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/proto.proto",
}
